version: "0.1"
name: debian_Focal
global_timeout: 1800
tasks:
  - name: "os-installation"
    worker: "{{.device_1}}"
    volumes:
      - /dev:/dev
      - /dev/console:/dev/console
      - /lib/firmware:/lib/firmware:ro
    actions:
      - name: "stream-ubuntu-image"
        image: image2disk:v1.0.0
        timeout: 600
        environment:
          DEST_DISK: /dev/sda
          IMG_URL: "http://192.168.50.4:8080/debian-11-generic-amd64.raw.gz"
          COMPRESSED: true
      - name: "install-openssl"
        image: cexec:v1.0.0
        timeout: 90
        environment:
          BLOCK_DEVICE: /dev/sda1
          FS_TYPE: ext4
          CHROOT: y
          DEFAULT_INTERPRETER: "/bin/sh -c"
          CMD_LINE: "apt -y update && apt -y install openssl"
      - name: "create-user"
        image: cexec:v1.0.0
        timeout: 90
        environment:
          BLOCK_DEVICE: /dev/sda1
          FS_TYPE: ext4
          CHROOT: y
          DEFAULT_INTERPRETER: "/bin/sh -c"
          CMD_LINE: "useradd -p $(openssl passwd -1 tink) -s /bin/bash -d /home/tink/ -m -G sudo tink"
      - name: "enable-ssh"
        image: cexec:v1.0.0
        timeout: 90
        environment:
          BLOCK_DEVICE: /dev/sda1
          FS_TYPE: ext4
          CHROOT: y
          DEFAULT_INTERPRETER: "/bin/sh -c"
          CMD_LINE: "ssh-keygen -A; systemctl enable ssh.service; sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config"
      - name: "add-sshkeysdir"
        image: cexec:v1.0.0
        timeout: 90
        environment:
          BLOCK_DEVICE: /dev/sda1
          FS_TYPE: ext4
          CHROOT: y
          DEFAULT_INTERPRETER: "/bin/sh -c"
          CMD_LINE: "mkdir -p /home/tink/.ssh; chown 1000:1000 /home/tink/.ssh; chmod 700 /home/tink/.ssh"
      - name: "write-sshkey"
        image: writefile:v1.0.0
        timeout: 90
        environment:
          DEST_DISK: /dev/sda1
          FS_TYPE: ext4
          DEST_PATH: /home/tink/.ssh/authorized_keys
          CONTENTS: |
            ssh-ed25519 AAAAC3NzaEXAMPLEUSER12345DhakND66yZo6LEGLRJ+JjqB0+bgaKW80W6bxv407PzS user@ssh.key
          UID: 1000
          GID: 1000
          MODE: 600
          DIRMODE: 0700
      - name: "write-sshconfig"
        image: writefile:v1.0.0
        timeout: 90
        environment:
          DEST_DISK: /dev/sda1
          FS_TYPE: ext4
          DEST_PATH: /etc/ssh/sshd_config.d/10-custom_conf
          CONTENTS: |
            PubkeyAuthentication yes
            PasswordAuthentication no
          UID: 0
          GID: 0
          MODE: 644
          DIRMODE: 0755